# Generated by Django 4.0.6 on 2024-09-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_discounts',
            name='is_timed',
            field=models.BooleanField(default=False),
        ),
    ]
