# Generated by Django 4.0.6 on 2024-09-02 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_tbl_discounts_is_timed'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountflag',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.tbl_discounts'),
        ),
    ]
