# Generated by Django 4.0.6 on 2024-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
