# Generated by Django 4.0.6 on 2024-07-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_customer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='loyalty_points',
            field=models.FloatField(default=0.0),
        ),
    ]
