# Generated by Django 4.0.6 on 2024-08-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_customer_loyalty_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='dob',
        ),
    ]
