# Generated by Django 4.0.6 on 2024-08-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_customer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='review_points',
            field=models.FloatField(default=0.0),
        ),
    ]
