# Generated by Django 4.0.6 on 2024-08-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_customer_review_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_points',
            field=models.FloatField(default=0.0),
        ),
    ]
