# Generated by Django 4.0.6 on 2024-08-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_customer_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customernormallogin',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
