# Generated by Django 4.0.6 on 2024-07-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menutype_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='promotional_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='menu',
            name='rating',
            field=models.DecimalField(choices=[(0.0, '0.0'), (0.5, '0.5'), (1.0, '1'), (1.5, '1.5'), (2.0, '2'), (2.5, '2.5'), (3.0, '3'), (3.5, '3.5'), (4.0, '4'), (4.5, '4.5'), (5.0, '5')], decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
