# Generated by Django 4.0.6 on 2024-08-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(null=True, upload_to='media_files/'),
        ),
    ]
