# Generated by Django 4.0.6 on 2024-08-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_menu_delete_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='review_points',
            field=models.FloatField(default=0.0),
        ),
    ]
