# Generated by Django 4.0.6 on 2024-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_tblredeemedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblredeemedproduct',
            name='outlet',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
