# Generated by Django 4.0.6 on 2024-08-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_hashvalue'),
        ('menu', '0018_tblredeemedproduct_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblredeemedproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
        migrations.AddField(
            model_name='tblredeemedproduct',
            name='state',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
    ]
