# Generated by Django 4.0.6 on 2024-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_tblredeemedproduct_order_tblredeemedproduct_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagmenu',
            name='send_payload_in_notification',
            field=models.BooleanField(default=False),
        ),
    ]
