# Generated by Django 4.0.6 on 2024-08-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_tbl_timedpromomenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='is_timed',
            field=models.BooleanField(default=False),
        ),
    ]
