# Generated by Django 4.0.6 on 2024-09-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_menutype_is_timed'),
    ]

    operations = [
        migrations.AddField(
            model_name='flagmenu',
            name='allow_discount',
            field=models.BooleanField(default=False),
        ),
    ]
