# Generated by Django 4.0.6 on 2024-09-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0023_flagmenu_allow_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization/images/'),
        ),
    ]
