# Generated by Django 4.0.6 on 2024-09-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_organization_address_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_veg',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='spice_level',
            field=models.DecimalField(blank=True, choices=[(1.0, '1'), (2.0, '2'), (3.0, '3'), (4.0, '4'), (5.0, '5')], decimal_places=1, max_digits=2, null=True),
        ),
    ]
