# Generated by Django 4.0.6 on 2024-09-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0025_menu_is_veg_menu_spice_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='organization/images'),
        ),
    ]
