# Generated by Django 4.0.6 on 2024-09-02 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_discountflag_discount'),
        ('order', '0014_remove_order_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billreqwithdiscount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='discounts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.tbl_discounts'),
        ),
    ]
