# Generated by Django 4.0.6 on 2024-09-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_hashvalue_qr_code_hashvalue_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
